In [15]:
import pandas as pd

# Load the player statistics data
player_stats = pd.read_csv("D:\java repository\R5D5-Project-dev\model\ML_Model_Dataset_02\complete_data_model_2k_ratings.csv")

# Create a new column for the player ID
player_stats['player_id'] = ''

# Loop over each row and assign a unique player ID
current_id = 1
for i, row in player_stats.iterrows():
    player_stats.at[i, 'player_id'] = f'M02{current_id:05}'
    current_id += 1

# Save the updated dataset to a new CSV file
player_stats.to_csv('complete_data_model_2k_ratings_with_id.csv', index=False)
player_stats.head()

,Close Shot,Mid-Range Shot,Three-Point Shot,Free Throw,Shot IQ,Offensive Consistency,Speed,Acceleration,Strength,Vertical,...,Steal,Block,Lateral Quickness,Help Defense IQ,Pass Perception,Defensive Consistency,Offensive Rebound,Defensive Rebound,salary,player_id
0,76,60,74,70,97,85,71,67,72,92,...,40,52,74,75,68,70,52,74,0.473311,M0200001
1,70,90,75,73,86,65,53,48,91,69,...,42,65,67,92,70,90,50,68,0.683705,M0200002
2,76,47,60,64,62,70,60,58,95,79,...,87,80,52,84,80,75,90,97,0.660252,M0200003
3,85,71,77,72,66,95,82,85,57,98,...,37,60,82,72,75,55,41,56,0.670896,M0200004
4,90,72,74,86,90,98,79,78,87,86,...,63,89,71,97,82,95,75,81,0.660252,M0200005

In [16]:
# Load the player statistics data
player_stats_sal = pd.read_csv("D:\java repository\R5D5-Project-dev\model\ML_Model_Dataset_02\y_train02.csv")

# Create a new column for the player ID
player_stats_sal['player_id'] = ''

# Loop over each row and assign a unique player ID
current_id = 1
for i, row in player_stats_sal.iterrows():
    player_stats_sal.at[i, 'player_id'] = f'M02{current_id:05}'
    current_id += 1

# Save the updated dataset to a new CSV file
player_stats_sal.to_csv('complete_data_model_2k_ratings_y_train_with_id.csv', index=False)
player_stats_sal.head()

     salary player_id
0  0.612813  M0200001
1  0.670896  M0200002
2  0.676982  M0200003
3  0.169482  M0200004
4  0.096728  M0200005

In [17]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# Load the data sets
salary_df = pd.read_csv("D:\java repository\R5D5-Project-dev\model\ML_Model_Dataset_02\y_train02.csv")
X_df = pd.read_csv("D:\java repository\R5D5-Project-dev\model\ML_Model_Dataset_02\X_train02.csv")

# Merge the data sets
merged_df = pd.concat([X_df, salary_df], axis=1)

# Calculate the correlation between the variables
corr_matrix = merged_df.corr()

# Select the variables that are most correlated with salary
selected_features = corr_matrix["salary"].sort_values(ascending=False).head(10).index

# Create the X and y data sets
X = merged_df[selected_features]
y = merged_df["salary"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Test the model
y_pred = model.predict(X_test)

# Evaluate the model
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
print("R^2 Score: ", r2)
print("MSE: ", mse)

R^2 Score:  1.0
MSE:  6.790278718210997e-32

In [18]:
# Get the correlation matrix
corr_matrix = merged_df.corr()

# Get the absolute correlations with the target variable
corr_with_salary = abs(corr_matrix['salary'])

# Sort the features by correlation with salary
sorted_features = corr_with_salary.sort_values(ascending=False)

# Print the feature names with the highest correlations
print(sorted_features[1:11].index.tolist())

['Hands', 'Stamina', 'Layup', 'Pass IQ', 'Pass Vision', 'Pass Accuracy', 'Pass Perception', 'Three-Point Shot', 'Mid-Range Shot', 'Overall Durability']

In [19]:
# Get the correlation matrix
corr_matrix = merged_df.corr()

# Get the correlations with the target variable
corr_with_salary = corr_matrix['salary']

# Sort the features by correlation with salary
sorted_features = corr_with_salary.sort_values(ascending=False)

# Print the feature names with their correlation values
print(sorted_features[1:11])

Hands                 0.425738
Stamina               0.369582
Layup                 0.342658
Pass IQ               0.313975
Pass Vision           0.309276
Pass Accuracy         0.290562
Pass Perception       0.288004
Three-Point Shot      0.250130
Mid-Range Shot        0.228736
Overall Durability    0.219172
Name: salary, dtype: float64

In [20]:
# Get the correlation matrix
corr_matrix = merged_df.corr()

# Get the correlations with the target variable
corr_with_salary = corr_matrix['salary']

# Sort the features by correlation with salary
sorted_features = corr_with_salary.sort_values(ascending=False)

# Print the feature names with their correlation values and descriptions
for feature, correlation in sorted_features[1:11].items():
    if correlation > 0.5:
        print(feature, "has a strong positive correlation with salary.")
    elif correlation > 0:
        print(feature, "has a positive correlation with salary.")
    elif correlation < -0.5:
        print(feature, "has a strong negative correlation with salary.")
    elif correlation < 0:
        print(feature, "has a negative correlation with salary.")

Hands has a positive correlation with salary.
Stamina has a positive correlation with salary.
Layup has a positive correlation with salary.
Pass IQ has a positive correlation with salary.
Pass Vision has a positive correlation with salary.
Pass Accuracy has a positive correlation with salary.
Pass Perception has a positive correlation with salary.
Three-Point Shot has a positive correlation with salary.
Mid-Range Shot has a positive correlation with salary.
Overall Durability has a positive correlation with salary.

In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import r2_score, mean_squared_error

# Load the data sets
salary_df = pd.read_csv('complete_data_model_2k_ratings_y_train_with_id.csv')
X_df = pd.read_csv("D:\java repository\R5D5-Project-dev\model\ML_Model_Dataset_02\X_train02.csv")

# Merge the data sets
merged_df = pd.concat([X_df, salary_df], axis=1)

# Get the top 6 features with the highest correlation with salary
top_features = ['Hands', 'Stamina', 'Layup', 'Pass IQ', 'Pass Vision', 'Pass Accuracy']

# Create the X and y data sets
X = merged_df[top_features]
y = merged_df["salary"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model = GradientBoostingRegressor(random_state=42)
model.fit(X_train, y_train)

# Test the model
y_pred = model.predict(X_test)

# Evaluate the model
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
print("R^2 Score: ", r2)
print("MSE: ", mse)

R^2 Score:  -0.08168607717773768
MSE:  0.08305525535122515